# Options for pvacFuse
pvacfuse_options:
  depth: 1000  # Minimum transcript coverage depth
  threads: 4  # Thread count for parallel execution
  epitope_lengths_1: [8, 9, 10, 11, 12, 13, 14, 15]
  epitope_lengths_2: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  threads: 20
  algorithms: "all"
